image_folder: "images"
unknowns_output_folder: "unknown"
valid_output_folder: "valid"
invalid_output_folder: "invalid"
model: "llava:7b"
prompt: |
  Analyze the provided image and evaluate its content based on the following criteria:
  1. If the image is of low quality (e.g., blurry, pixelated), contains a screenshot,
  is an extract from a website or web application, or contains only text, classify it as INVALID.
  2. If none of the above issues apply and the image meets acceptable standards, classify it as VALID.