image_folder: "images"
unknowns_output_folder: "unknown"
valid_output_folder: "valid"
invalid_output_folder: "invalid"
model: "llava:7b"
prompt: |
  You will only respond with 'VALID', 'INVALID', 'UNKNOWN' in capital letter based on following rules:
  - Image is blurred => INVALID
  - Image looks like a screenshot => INVALID
  - Image contains a lot of text => INVALID
  - Image has no element visible => UNKNOWN

  I don't need any other information nor explanation. Remove extra spaces.