image_folder: "images"
unknowns_output_folder: "unknown"
valid_output_folder: "valid"
invalid_output_folder: "invalid"
model: "llava:7b"
prompt: |
  You need to classify the image. Image is INVALID if on the following criteria is meet:
    - Image is a screenshot
    - Image is an extract from a website or web application
    - Image contains only text
    - Image has low quality
  Do not repeat rules but provide criteria that is meet and add the classification word. Remove any extra spaces.